// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBiPm7M-XhaVBWuryAVsWNOqCaapWpWfT4',
    appId: '1:676074844128:web:0bd738dc4622e1358b4585',
    messagingSenderId: '676074844128',
    projectId: 'layers-skins',
    authDomain: 'layers-skins.firebaseapp.com',
    storageBucket: 'layers-skins.appspot.com',
    measurementId: 'G-7X70JVSM7H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAwZQ4On5T-sHaJtoxhk3zpWIOxJXeKlEw',
    appId: '1:676074844128:android:d58827cc27944fd28b4585',
    messagingSenderId: '676074844128',
    projectId: 'layers-skins',
    storageBucket: 'layers-skins.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCYCkJfEVUjFFkDB6aSjaA6K-k0s4WWpZ8',
    appId: '1:676074844128:ios:91aab90bf170b9348b4585',
    messagingSenderId: '676074844128',
    projectId: 'layers-skins',
    storageBucket: 'layers-skins.appspot.com',
    iosClientId:
        '676074844128-6kj8psmcat7ga20deb42hpviat0mhqsl.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCYCkJfEVUjFFkDB6aSjaA6K-k0s4WWpZ8',
    appId: '1:676074844128:ios:91aab90bf170b9348b4585',
    messagingSenderId: '676074844128',
    projectId: 'layers-skins',
    storageBucket: 'layers-skins.appspot.com',
    iosClientId:
        '676074844128-6kj8psmcat7ga20deb42hpviat0mhqsl.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication2',
  );
}
